export type Difficulty = "Easy" | "Medium" | "Hard";
export type Status = "solved" | "attempted" | "unsolved";

export interface Problem {
  id: number;
  title: string;
  difficulty: Difficulty;
  tags: string[];
  acceptance: number; // percentage
  submissions: number;
  status: Status;
}

export const MOCK_PROBLEMS: Problem[] = [
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    tags: ["Array", "Hash Table"],
    acceptance: 51.2,
    submissions: 14820000,
    status: "solved",
  },
  {
    id: 2,
    title: "Add Two Numbers",
    difficulty: "Medium",
    tags: ["Linked List", "Math"],
    acceptance: 42.1,
    submissions: 9400000,
    status: "attempted",
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    tags: ["String", "Sliding Window", "Hash Table"],
    acceptance: 34.8,
    submissions: 11600000,
    status: "solved",
  },
  {
    id: 4,
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    tags: ["Array", "Binary Search", "Divide and Conquer"],
    acceptance: 38.5,
    submissions: 6200000,
    status: "unsolved",
  },
  {
    id: 5,
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    tags: ["String", "DP"],
    acceptance: 33.4,
    submissions: 8100000,
    status: "attempted",
  },
  {
    id: 6,
    title: "Zigzag Conversion",
    difficulty: "Medium",
    tags: ["String"],
    acceptance: 46.1,
    submissions: 4300000,
    status: "unsolved",
  },
  {
    id: 7,
    title: "Reverse Integer",
    difficulty: "Medium",
    tags: ["Math"],
    acceptance: 27.8,
    submissions: 10200000,
    status: "solved",
  },
  {
    id: 8,
    title: "String to Integer (atoi)",
    difficulty: "Medium",
    tags: ["String", "Math"],
    acceptance: 17.9,
    submissions: 8800000,
    status: "unsolved",
  },
  {
    id: 9,
    title: "Palindrome Number",
    difficulty: "Easy",
    tags: ["Math"],
    acceptance: 54.7,
    submissions: 12300000,
    status: "solved",
  },
  {
    id: 10,
    title: "Regular Expression Matching",
    difficulty: "Hard",
    tags: ["String", "DP", "Recursion"],
    acceptance: 28.1,
    submissions: 5500000,
    status: "unsolved",
  },
  {
    id: 11,
    title: "Container With Most Water",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Greedy"],
    acceptance: 54.3,
    submissions: 7900000,
    status: "solved",
  },
  {
    id: 12,
    title: "Integer to Roman",
    difficulty: "Medium",
    tags: ["Math", "String"],
    acceptance: 66.0,
    submissions: 5100000,
    status: "solved",
  },
  {
    id: 13,
    title: "Roman to Integer",
    difficulty: "Easy",
    tags: ["Math", "String"],
    acceptance: 59.9,
    submissions: 9700000,
    status: "solved",
  },
  {
    id: 14,
    title: "Longest Common Prefix",
    difficulty: "Easy",
    tags: ["String", "Trie"],
    acceptance: 42.6,
    submissions: 8300000,
    status: "attempted",
  },
  {
    id: 15,
    title: "3Sum",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Sorting"],
    acceptance: 32.1,
    submissions: 10800000,
    status: "attempted",
  },
  {
    id: 16,
    title: "3Sum Closest",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Sorting"],
    acceptance: 45.8,
    submissions: 4900000,
    status: "unsolved",
  },
  {
    id: 17,
    title: "Letter Combinations of a Phone Number",
    difficulty: "Medium",
    tags: ["String", "Backtracking"],
    acceptance: 57.0,
    submissions: 6600000,
    status: "solved",
  },
  {
    id: 18,
    title: "4Sum",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Sorting"],
    acceptance: 37.2,
    submissions: 4100000,
    status: "unsolved",
  },
  {
    id: 19,
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    tags: ["Linked List", "Two Pointers"],
    acceptance: 42.5,
    submissions: 7200000,
    status: "solved",
  },
  {
    id: 20,
    title: "Valid Parentheses",
    difficulty: "Easy",
    tags: ["String", "Stack"],
    acceptance: 40.8,
    submissions: 11500000,
    status: "solved",
  },
  {
    id: 21,
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    tags: ["Linked List", "Recursion"],
    acceptance: 63.7,
    submissions: 10100000,
    status: "solved",
  },
  {
    id: 22,
    title: "Generate Parentheses",
    difficulty: "Medium",
    tags: ["String", "DP", "Backtracking"],
    acceptance: 74.3,
    submissions: 5800000,
    status: "attempted",
  },
  {
    id: 23,
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    tags: ["Linked List", "Divide and Conquer", "Heap"],
    acceptance: 51.6,
    submissions: 5200000,
    status: "unsolved",
  },
  {
    id: 24,
    title: "Swap Nodes in Pairs",
    difficulty: "Medium",
    tags: ["Linked List", "Recursion"],
    acceptance: 64.5,
    submissions: 4600000,
    status: "unsolved",
  },
  {
    id: 25,
    title: "Reverse Nodes in k-Group",
    difficulty: "Hard",
    tags: ["Linked List", "Recursion"],
    acceptance: 60.2,
    submissions: 3900000,
    status: "unsolved",
  },
];

export const ALL_TAGS = [
  "Array",
  "String",
  "Hash Table",
  "DP",
  "Math",
  "Sorting",
  "Greedy",
  "Binary Search",
  "Two Pointers",
  "Sliding Window",
  "Backtracking",
  "Linked List",
  "Stack",
  "Graph",
  "Tree",
  "Heap",
  "Recursion",
  "Trie",
  "Divide and Conquer",
];
